### ISSUE TITLE
Please define a license

### ISSUE THREAD

**Issue by tcblight** [avvo/intransient_capybara#3]
Hi! I found this project through this article: http://engineering.avvo.com/articles/transient-capybara-tests.html

I'm interested in using it at work, but you don't appear to have a license defined, and my work is very strict about making sure we are working with properly licensed third party code.

If you need suggestions for a license, we seem to be fond of the [Apache 2.0 license](https://opensource.org/licenses/apache2.0.php) and the [MIT license](https://opensource.org/licenses/mit-license.php)

Would you mind uploading a license to your repository?

**Comment by matt9986** [comment]
Done! (#4 ) Hope it helps
